// Constantes para tipos de servicios disponibles en la aplicación
// Centraliza las opciones de servicios para mantener consistencia

export const SERVICE_TYPES = [
  // Tecnología y Software
  'Desarrollo de software',
  'Desarrollo móvil',
  'Desarrollo web',
  'Diseño web',
  'E-commerce',
  'Testing de software',
  'DevOps',
  'Cloud computing',
  'Inteligencia artificial',
  'Machine Learning',
  'Big Data',
  'Análisis de datos',
  'Ciberseguridad',
  'Soporte técnico',
  'Consultoría IT',
  'Automatización',
  'Blockchain',
  'IoT (Internet de las cosas)',
  'Realidad virtual',
  'Realidad aumentada',
  
  // Marketing y Comunicación
  'Marketing digital',
  'SEO',
  'SEM',
  'Redes sociales',
  'Publicidad',
  'Content Marketing',
  'Email Marketing',
  'Influencer Marketing',
  'Marketing de afiliados',
  'Marketing automation',
  'Analytics y métricas',
  'Branding',
  'Identidad corporativa',
  'Comunicación corporativa',
  'Relaciones públicas',
  'Eventos corporativos',
  
  // Diseño y Creatividad
  'Diseño gráfico',
  'UX/UI Design',
  'Diseño de productos',
  'Diseño industrial',
  'Fotografía',
  'Video producción',
  'Animación',
  'Ilustración',
  'Diseño de interiores',
  'Arquitectura',
  'Diseño de moda',
  'Diseño de packaging',
  'Diseño editorial',
  'Diseño de logotipos',
  
  // Negocios y Consultoría
  'Consultoría',
  'Consultoría estratégica',
  'Consultoría financiera',
  'Consultoría organizacional',
  'Consultoría de procesos',
  'Gestión de proyectos',
  'Gestión de calidad',
  'Auditoría',
  'Análisis de mercado',
  'Investigación de mercado',
  'Plan de negocios',
  'Franchising',
  'Mentoring empresarial',
  
  // Recursos Humanos
  'Recursos humanos',
  'Reclutamiento',
  'Capacitación',
  'Desarrollo organizacional',
  'Coaching ejecutivo',
  'Evaluación de desempeño',
  'Políticas de RRHH',
  'Outsourcing de RRHH',
  'Headhunting',
  'Assessment center',
  
  // Finanzas y Contabilidad
  'Contabilidad',
  'Financiero',
  'Auditoría financiera',
  'Análisis financiero',
  'Inversiones',
  'Seguros',
  'Banca',
  'Factoring',
  'Leasing',
  'Asesoría fiscal',
  'Contabilidad de costos',
  'Control de gestión',
  'Treasury management',
  
  // Legal
  'Legal',
  'Derecho corporativo',
  'Derecho laboral',
  'Derecho fiscal',
  'Derecho comercial',
  'Propiedad intelectual',
  'Derecho inmobiliario',
  'Derecho internacional',
  'Mediación',
  'Arbitraje',
  'Compliance',
  'Due diligence',
  
  // Operaciones y Logística
  'Logística',
  'Cadena de suministro',
  'Almacenamiento',
  'Distribución',
  'Transporte',
  'Importación/Exportación',
  'Aduanas',
  'Inventarios',
  'Procurement',
  'Gestión de proveedores',
  'Optimización de procesos',
  'Lean manufacturing',
  'Six Sigma',
  
  // Ventas y Comercial
  'Ventas',
  'Desarrollo de ventas',
  'Telemarketing',
  'Ventas B2B',
  'Ventas B2C',
  'Marketplace management',
  'Customer success',
  'Retención de clientes',
  'Fidelización',
  'CRM',
  'Sales automation',
  
  // Servicios Especializados
  'Traducción',
  'Interpretación',
  'Localización',
  'Transcripción',
  'Investigación',
  'Estudios de mercado',
  'Encuestas',
  'Focus groups',
  'Análisis estadístico',
  'Consultoría especializada',
  'Asesoría técnica',
  'Peritaje',
  'Certificaciones',
  
  // Inmobiliario y Construcción
  'Inmobiliario',
  'Construcción',
  'Ingeniería civil',
  'Remodelación',
  'Mantenimiento',
  'Instalaciones eléctricas',
  'Plomería',
  'Carpintería',
  'Pintura',
  'Jardinería',
  'Limpieza',
  'Seguridad física',
  
  // Salud y Bienestar
  'Salud',
  'Medicina',
  'Odontología',
  'Psicología',
  'Fisioterapia',
  'Nutrición',
  'Bienestar corporativo',
  'Prevención de riesgos',
  'Salud ocupacional',
  'Medicina del trabajo',
  'Terapias alternativas',
  'Coaching de vida',
  
  // Educación y Capacitación
  'Educación',
  'E-learning',
  'Desarrollo de contenido educativo',
  'Tutoring',
  'Idiomas',
  'Certificaciones profesionales',
  'Formación técnica',
  'Soft skills',
  'Liderazgo',
  'Coaching',
  'Mentoring',
  
  // Industrias Específicas
  'Manufactura',
  'Agricultura',
  'Ganadería',
  'Pesca',
  'Minería',
  'Energía',
  'Petróleo y gas',
  'Química',
  'Farmacéutica',
  'Alimentación',
  'Bebidas',
  'Textil',
  'Moda',
  'Automotriz',
  'Aerospace',
  'Electrónica',
  'Telecomunicaciones',
  
  // Servicios de Apoyo
  'Catering',
  'Eventos',
  'Fotografía de eventos',
  'Video de eventos',
  'Sonido e iluminación',
  'Decoración',
  'Floristería',
  'Transporte ejecutivo',
  'Mensajería',
  'Courier',
  
  // Servicios Profesionales
  'Consultoría de imagen',
  'Etiqueta empresarial',
  'Protocolo',
  'Organización de eventos',
  'Wedding planning',
  'Personal shopper',
  'Concierge',
  'Asistencia virtual',
  'Secretaría ejecutiva',
  'Asistencia administrativa',
  'Gestión de oficina',
  'Receptionist',
  
  // Tecnologías Emergentes
  'Innovación',
  'I+D (Investigación y Desarrollo)',
  'Patentes',
  'Transferencia de tecnología',
  'Startup consulting',
  'Venture capital',
  'Business angels',
  'Crowdfunding',
  'Fintech',
  'Insurtech',
  'PropTech',
  'HealthTech',
  'EdTech',
  'AgriTech',
  'CleanTech',
] as const;

export type ServiceType = typeof SERVICE_TYPES[number];

// Función para obtener servicios filtrados por término de búsqueda
export const getFilteredServices = (searchTerm: string): string[] => {
  if (!searchTerm) return [...SERVICE_TYPES];
  
  return SERVICE_TYPES.filter(service =>
    service.toLowerCase().includes(searchTerm.toLowerCase())
  );
};

// Función para obtener servicios populares (primeros 10)
export const getPopularServices = (): string[] => {
  return [...SERVICE_TYPES.slice(0, 10)];
};
